function getDogList() {
  return [
    "affenpinscher",
    "african",
    "airedale",
    "akita",
    "appenzeller",
    "shepherd australian",
    "basenji",
    "beagle",
    "bluetick",
    "borzoi",
    "bouvier",
    "boxer",
    "brabancon",
    "briard",
    "norwegian buhund",
    "boston bulldog",
    "english bulldog",
    "french bulldog",
    "staffordshire bullterrier",
    "husky",
    "keeshond",
    "kelpie",
    "komondor",
    "kuvasz",
    "labrador",
    "leonberg",
    "lhasa",
    "malamute",
    "malinois",
    "maltese",
    "cairn",
    "australian cattledog",
    "chihuahua",
    "chow",
    "clumber",
    "cockapoo",
    "border collie",
    "coonhound",
    "cardigan corgi",
    "cotondetulear",
    "dachshund",
    "dalmatian",
    "great dane",
    "scottish deerhound",
    "dhole",
    "dingo",
    "doberman",
    "norwegian elkhound",
    "american terrier",
    "australian terrier",
    "bedlington terrier",
    "border terrier",
    "dandie terrier",
    "fox terrier",
    "irish terrier",
    "kerryblue terrier",
    "lakeland terrier",
    "norfolk terrier",
    "norwich terrier",
    "patterdale terrier",
    "russell terrier",
    "scottish terrier",
    "sealyham terrier",
    "silky terrier",
    "tibetan terrier",
    "toy terrier",
    "westhighland terrier",
    "wheaten terrier",
    "yorkshire terrier",
    "afghan hound",
    "basset hound",
    "blood hound",
    "english hound",
    "ibizan hound",
    "plott hound",
    "walker hound",
    "blenheim spaniel",
    "brittany spaniel",
    "cocker spaniel",
    "irish spaniel",
    "japanese spaniel",
    "sussex spaniel",
    "welsh spaniel",
    "papillon",
    "pekinese",
    "pembroke",
    "entlebucher",
    "eskimo",
    "lapphund finnish",
    "bichon frise",
    "germanshepherd",
    "italian greyhound",
    "groenendael",
    "havanese",
    "bull mastiff",
    "english mastiff",
    "tibetan mastiff",
    "mexicanhairless",
    "mix",
    "bernese mountain",
    "swiss mountain",
    "newfoundland",
    "otterhound",
    "caucasian ovcharka",
    "miniature pinscher",
    "pitbull",
    "german pointer",
    "germanlonghair pointer",
    "pug",
    "puggle",
    "pyrenees",
    "redbone",
    "pomeranian",
    "rottweiler",
    "saluki",
    "samoyed",
    "schipperke",
    "miniature poodle",
    "standard poodle",
    "toy poodle",
    "chesapeake retriever ",
    "curly retriever",
    "flatcoated retriever",
    "golden retriever",
    "shiba",
    "shihtzu",
    "rhodesian ridgeback",
    "giant schnauzer",
    "miniature schnauzer",
    "english setter",
    "gordon setter",
    "irish setter",
    "english sheepdog",
    "shetland sheepdog",
    "stbernard",
    "spanish waterdog",
    "vizsla",
    "english springer",
    "weimaraner",
    "whippet",
    "irish wolfhound",
  ];
}
